Folder.create(title: "Archived", description: "Find out more about the success of our previous projects!", started: "2019-08-06")
Folder.create(title: "Renew Waldorf Square", description: "The iconic Waldorf Square is up for a complete renewal. And we want to learn what you think should be done.", started: "2019-10-27")
Folder.create(title: "Heritage", description: "There is a strong 'islander' identity and a deep commitment to the stewardship of our remarkable natural environment. We take pride and pleasure in living in a resilient community that celebrates its arts, culture and heritage. We highly value and want to preserve our small community way of living, removed from the traffic and distractions of urban life. In recent years, we have turned our attention to how, as islanders, we can live in a more inclusive and sustainable way.", started: "2019-08-06")
Folder.create(title: "Old offline projects", description: "Before we had this platform, we did quite some offline-only participation projects. We grouped them here.", started: "2010-04-16")
Folder.create(title: "Nested folder", description: "This folder is nested", started: "2020-04-16", parent_folder_id: 1)

Project.create(title: "Poll on the new walkway", description: "The municipality is currently investigating the added value of a pedestrian street from the parking lot, crossing the toad pond, to finally reach Gonzo street. A first draft has already been made for this and it is also known how high the costs are for the construction of such a bridge.", started: "2019-12-01", cost: "562", folder: Folder.find(2))
Project.create(title: "Reviewing our guidance on how we regulate services for people with a learning disability and/or autism", description: "Reviewing our guidance on how we regulate services for people with a learning disability and/or autism", started: "2019-10-01", cost: "145")
Project.create(title: "Survey for a play pool", description: "Let your opinion be heard about a play pool in Waldorf Square! As an outcome of the project: \"Launch your ideas for an even more livable Kermitfort\", the idea was introduced by residents to place play pools.", started: "2018-12-01", cost: "1000", folder: Folder.find(3))
Project.create(title: "Heritage Inventory and Stories Collection", description: "Share your favourite places and stories that are (or should be) part of the heritage of Kermitfort.", started: "2020-01-01", cost: "794", folder: Folder.find(3))
Project.create(title: "Activity benches", description: "In order to make Kermitforters exercise more, the city wants to install IPitup moving benches everywhere across Kermitfort. You determine where they should be installed.", started: "2020-08-21", cost: "1231")
Project.create(title: "Consultation on \"Wifi for everyone\"", description: "Take part in choosing free wifi zones in the city!", started: "2020-02-21", cost: "1405", folder: Folder.find(1))
Project.create(title: "Testing 123 For everyone", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum ", started: "2020-02-20", cost: "10")
Project.create(title: "Lalala Lalala", description: "Havenus HavenusHavenus Havenus HavenusHavenus Havenus", started: "2021-02-20", cost: "100")
Project.create(title: "Project Happy", description: "Proprietor Proprietor Proprietor Proprietor", started: "2020-03-20", cost: "130")

topic_green = Topic.create(title: "Green")
topic_infra = Topic.create(title: "Infrastructure")
topic_house = Topic.create(title: "Housing")
topic_culture = Topic.create(title: "Culture")
topic_youth = Topic.create(title: "Youth")
topic_mobility = Topic.create(title: "Mobility")
topic_health = Topic.create(title: "Health")
topic_env = Topic.create(title: "Environment")

ProjectTopic.create(project_id: 1, topic_id: 2)
ProjectTopic.create(project_id: 1, topic_id: 3)
ProjectTopic.create(project_id: 2, topic_id: 2)
ProjectTopic.create(project_id: 3, topic_id: 6)
ProjectTopic.create(project_id: 6, topic_id: 1)
ProjectTopic.create(project_id: 5, topic_id: 2)
ProjectTopic.create(project_id: 4, topic_id: 4)
ProjectTopic.create(project_id: 4, topic_id: 5)
ProjectTopic.create(project_id: 5, topic_id: 6)
ProjectTopic.create(project_id: 4, topic_id: 7)
ProjectTopic.create(project_id: 7, topic_id: 1)
ProjectTopic.create(project_id: 8, topic_id: 4)
ProjectTopic.create(project_id: 9, topic_id: 3)
ProjectTopic.create(project_id: 9, topic_id: 5)
ProjectTopic.create(project_id: 7, topic_id: 2)
ProjectTopic.create(project_id: 8, topic_id: 2)